ALTER TABLE site_visitors ALTER COLUMN dtype DROP DEFAULT, ALTER COLUMN date_of_registration DROP DEFAULT,
ALTER COLUMN email DROP DEFAULT, ALTER COLUMN is_activated DROP DEFAULT, ALTER COLUMN password DROP DEFAULT,
ALTER COLUMN comments_allowed DROP DEFAULT, ALTER COLUMN description DROP DEFAULT, ALTER COLUMN activation_code DROP DEFAULT;

ALTER TABLE tracks ALTER COLUMN date_of_release DROP DEFAULT, ALTER COLUMN description DROP DEFAULT,
ALTER COLUMN is_free DROP DEFAULT, ALTER COLUMN price DROP DEFAULT;

