INSERT INTO images (id, image_url) values (1,'Pop.jpg');
INSERT INTO images (id, image_url) values (2,'Trance.jpg');
INSERT INTO images (id, image_url) values (3,'Rock.jpg');
INSERT INTO images (id, image_url) values (4,'Metal.jpg');
INSERT INTO images (id, image_url) values (5,'Rap.jpg');
INSERT INTO images (id, image_url) values (6,'Techno.jpg');
INSERT INTO images (id, image_url) values (7,'Electro.jpg');
INSERT INTO images (id, image_url) values (8,'Alternative.jpg');
INSERT INTO images (id, image_url) values (9,'Blues.png');
INSERT INTO images (id, image_url) values (10,'DrumAndBass.jpg');
INSERT INTO images (id, image_url) values (11,'Folk.jpg');
INSERT INTO images (id, image_url) values (12,'Funk.jpg');
INSERT INTO images (id, image_url) values (13,'HipHop.jpg');
INSERT INTO images (id, image_url) values (14,'House.jpg');
INSERT INTO images (id, image_url) values (15,'Indie.jpg');
INSERT INTO images (id, image_url) values (16,'Industrial.jpg');
INSERT INTO images (id, image_url) values (17,'Jazz.jpg');
INSERT INTO images (id, image_url) values (18,'NewAge.jpg');
INSERT INTO images (id, image_url) values (19,'Psy.jpg');
INSERT INTO images (id, image_url) values (20,'RnB.jpg');
INSERT INTO images (id, image_url) values (21,'Soul.jpg');
INSERT INTO images (id, image_url) values (22,'30secondstomars.jpg');
INSERT INTO images (id, image_url) values (23,'linkinpark.jpg');
INSERT INTO images (id, image_url) values (24,'muse.jpg');
INSERT INTO images (id, image_url) values (25,'mychemicalromance.jpg');
INSERT INTO images (id, image_url) values (26,'oasis.jpg');
INSERT INTO images (id, image_url) values (27,'redhotchilipeppers.jpg');
INSERT INTO images (id, image_url) values (28,'thecranberries.jpg');
INSERT INTO images (id, image_url) values (29,'thecure.jpg');
INSERT INTO images (id, image_url) values (30,'thesmashingpumpkins.jpg');
INSERT INTO images (id, image_url) values (31 ,'threedaysgrace.jpg');
INSERT INTO images (id, image_url) values (32,'bbking.jpg');
INSERT INTO images (id, image_url) values (33 ,'ericclapton.jpeg');
INSERT INTO images (id, image_url) values (34,'freddieking.jpg');
INSERT INTO images (id, image_url) values (35 ,'janisjoplin.jpg');
INSERT INTO images (id, image_url) values (36,'jimihendrix.jpg');
INSERT INTO images (id, image_url) values (37 ,'joebonamassa.jpg');
INSERT INTO images (id, image_url) values (38 ,'leonardcohen.jpg');
INSERT INTO images (id, image_url) values (39 ,'muddywaters.png');
INSERT INTO images (id, image_url) values (40 ,'raycharles.jpg');
INSERT INTO images (id, image_url) values (41 ,'tomwaits.jpg');
INSERT INTO images (id, image_url) values (42 ,'apex.jpg');
INSERT INTO images (id, image_url) values (43 ,'bes.jpg');
INSERT INTO images (id, image_url) values (44 ,'blacksunempire.jpg');
INSERT INTO images (id, image_url) values (45 ,'highcontrast.jpg');
INSERT INTO images (id, image_url) values (46 ,'logistics.jpg');
INSERT INTO images (id, image_url) values (47 ,'noisia.jpg');
INSERT INTO images (id, image_url) values (48 ,'pendulum.jpg');
INSERT INTO images (id, image_url) values (49 ,'receptor.jpg');
INSERT INTO images (id, image_url) values (50 ,'teebee.jpg');
INSERT INTO images (id, image_url) values (51 ,'thepanacea.jpg');
INSERT INTO images (id, image_url) values (52 ,'afrojack.jpg');
INSERT INTO images (id, image_url) values (53 ,'chuckie.jpg');
INSERT INTO images (id, image_url) values (54 ,'dadalife.jpg');
INSERT INTO images (id, image_url) values (55 ,'deadmouse.jpg');
INSERT INTO images (id, image_url) values (56 ,'heikoandmaiko.jpg');
INSERT INTO images (id, image_url) values (57 ,'klaas.jpg');
INSERT INTO images (id, image_url) values (58 ,'sebastianingrosso.jpg');
INSERT INTO images (id, image_url) values (59 ,'sebastianleger.jpg');
INSERT INTO images (id, image_url) values (60 ,'tocadisco.jpg');
INSERT INTO images (id, image_url) values (61 ,'wolfganggartner.jpg');
INSERT INTO images (id, image_url) values (62 ,'bobdylan.jpg');
INSERT INTO images (id, image_url) values (63 ,'brucespringsteen.jpg');
INSERT INTO images (id, image_url) values (64 ,'catstevens.jpg');
INSERT INTO images (id, image_url) values (65 ,'elliotsmith.jpg');
INSERT INTO images (id, image_url) values (66 ,'fleetfoxes.jpg');
INSERT INTO images (id, image_url) values (67 ,'ironandwine.jpg');
INSERT INTO images (id, image_url) values (68 ,'johnnycash.jpg');
INSERT INTO images (id, image_url) values (69 ,'jonimitchell.jpg');
INSERT INTO images (id, image_url) values (70 ,'neilyoung.jpg');
INSERT INTO images (id, image_url) values (71 ,'nickdrake.jpg');
INSERT INTO images (id, image_url) values (72 ,'algreen.png');
INSERT INTO images (id, image_url) values (73 ,'curtismayfield.jpg');
INSERT INTO images (id, image_url) values (74 ,'funkadelic.jpg');
INSERT INTO images (id, image_url) values (75 ,'georgeduke.jpg');
INSERT INTO images (id, image_url) values (76 ,'jamesbrown.jpg');
INSERT INTO images (id, image_url) values (77 ,'jamiroquai.jpg');
INSERT INTO images (id, image_url) values (78 ,'lennykravitz.jpg');
INSERT INTO images (id, image_url) values (79 ,'marvingaye.jpg');
INSERT INTO images (id, image_url) values (80 ,'prince.jpg');
INSERT INTO images (id, image_url) values (81 ,'steviewonder.jpg');
INSERT INTO images (id, image_url) values (82 ,'akon.jpg');
INSERT INTO images (id, image_url) values (83 ,'beastieboyz.jpg');
INSERT INTO images (id, image_url) values (84 ,'flyinglotus.jpg');
INSERT INTO images (id, image_url) values (85 ,'jayz.jpg');
INSERT INTO images (id, image_url) values (86 ,'lilwayne.jpg');
INSERT INTO images (id, image_url) values (87 ,'lupefiasco.jpg');
INSERT INTO images (id, image_url) values (88 ,'missyelliot.jpg');
INSERT INTO images (id, image_url) values (89 ,'snoopdogg.jpg');
INSERT INTO images (id, image_url) values (90 ,'timbaland.jpg');
INSERT INTO images (id, image_url) values (91 ,'wutangclan.jpg');
INSERT INTO images (id, image_url) values (92 ,'alexgaudino.jpg');
INSERT INTO images (id, image_url) values (93 ,'avicii.jpg');
INSERT INTO images (id, image_url) values (94 ,'bennybenassi.jpg');
INSERT INTO images (id, image_url) values (95 ,'chemicalbrothers.jpg');
INSERT INTO images (id, image_url) values (96 ,'daftpunk.jpg');
INSERT INTO images (id, image_url) values (97 ,'davidguetta.jpg');
INSERT INTO images (id, image_url) values (98 ,'faithless.jpg');
INSERT INTO images (id, image_url) values (99 ,'feddelegrand.jpg');
INSERT INTO images (id, image_url) values (100 ,'kaskade.png');
INSERT INTO images (id, image_url) values (101,'swedishhousemafia.jpg');
INSERT INTO images (id, image_url) values (102 ,'arcticmonkeys.jpg');
INSERT INTO images (id, image_url) values (103 ,'coldplay.png');
INSERT INTO images (id, image_url) values (104 ,'franzferdinand.jpg');
INSERT INTO images (id, image_url) values (105 ,'hozier.jpg');
INSERT INTO images (id, image_url) values (106 ,'kasabian.jpg');
INSERT INTO images (id, image_url) values (107 ,'morrissey.jpg');
INSERT INTO images (id, image_url) values (108 ,'placebo.jpg');
INSERT INTO images (id, image_url) values (109 ,'radiohead.jpg');
INSERT INTO images (id, image_url) values (110 ,'smiths.jpg');
INSERT INTO images (id, image_url) values (111 ,'xx.jpg');
INSERT INTO images (id, image_url) values (112 ,'cabaretvoltaire.jpg');
INSERT INTO images (id, image_url) values (113 ,'combichrist.jpg');
INSERT INTO images (id, image_url) values (114 ,'kmfdm.jpg');
INSERT INTO images (id, image_url) values (115 ,'laibach.jpg');
INSERT INTO images (id, image_url) values (116 ,'marilynmanson.jpg');
INSERT INTO images (id, image_url) values (117 ,'nachtmahr.jpg');
INSERT INTO images (id, image_url) values (118 ,'rammstein.jpg');
INSERT INTO images (id, image_url) values (119 ,'robzombie.jpg');
INSERT INTO images (id, image_url) values (120 ,'skinnypuppy.jpg');
INSERT INTO images (id, image_url) values (121 ,'suicidecommando.jpg');
INSERT INTO images (id, image_url) values (122 ,'amywinehouse.jpg');
INSERT INTO images (id, image_url) values (123 ,'arethafranklin.jpg');
INSERT INTO images (id, image_url) values (124 ,'bennygoodman.jpg');
INSERT INTO images (id, image_url) values (125 ,'billieholiday.jpg');
INSERT INTO images (id, image_url) values (126 ,'dukeellington.jpg');
INSERT INTO images (id, image_url) values (127 ,'ellafitzerald.jpg');
INSERT INTO images (id, image_url) values (128 ,'franksinatra.jpg');
INSERT INTO images (id, image_url) values (129 ,'louisarmstrong.jpg');
INSERT INTO images (id, image_url) values (130 ,'ninasimone.jpg');
INSERT INTO images (id, image_url) values (131 ,'zaz.jpg');
INSERT INTO images (id, image_url) values (132 ,'acdc.jpg');
INSERT INTO images (id, image_url) values (133 ,'apocalyptica.jpg');
INSERT INTO images (id, image_url) values (134 ,'godsmack.png');
INSERT INTO images (id, image_url) values (135 ,'ironmaiden.jpg');
INSERT INTO images (id, image_url) values (136 ,'korn.jpg');
INSERT INTO images (id, image_url) values (137 ,'metallica.jpg');
INSERT INTO images (id, image_url) values (138 ,'nightwish.jpg');
INSERT INTO images (id, image_url) values (139 ,'slayer.jpg');
INSERT INTO images (id, image_url) values (140 ,'slipknot.jpg');
INSERT INTO images (id, image_url) values (141 ,'systemofadown.jpg');
INSERT INTO images (id, image_url) values (142 ,'delerium.jpg');
INSERT INTO images (id, image_url) values (143 ,'enigma.jpg');
INSERT INTO images (id, image_url) values (144 ,'enya.jpg');
INSERT INTO images (id, image_url) values (145 ,'gregorian.jpg');
INSERT INTO images (id, image_url) values (146 ,'jeanmicheljarre.jpg');
INSERT INTO images (id, image_url) values (147 ,'mikeoldfield.jpg');
INSERT INTO images (id, image_url) values (148 ,'secretgarden.jpg');
INSERT INTO images (id, image_url) values (149 ,'vangelis.jpg');
INSERT INTO images (id, image_url) values (150 ,'yanni.jpg');
INSERT INTO images (id, image_url) values (151 ,'yiruma.jpg');
INSERT INTO images (id, image_url) values (152 ,'adamwalker.jpg');
INSERT INTO images (id, image_url) values (153 ,'adele.jpg');
INSERT INTO images (id, image_url) values (154 ,'britneyspears.jpg');
INSERT INTO images (id, image_url) values (155 ,'brunomars.jpg');
INSERT INTO images (id, image_url) values (156 ,'edsheeran.jpg');
INSERT INTO images (id, image_url) values (157 ,'imaginedragons.jpg');
INSERT INTO images (id, image_url) values (158 ,'katyperry.jpg');
INSERT INTO images (id, image_url) values (159 ,'ladygaga.jpg');
INSERT INTO images (id, image_url) values (160 ,'maroon5.png');
INSERT INTO images (id, image_url) values (161 ,'shakira.jpg');
INSERT INTO images (id, image_url) values (162 ,'astralprojection.jpg');
INSERT INTO images (id, image_url) values (163 ,'astrix.jpg');
INSERT INTO images (id, image_url) values (164 ,'gms.jpg');
INSERT INTO images (id, image_url) values (165 ,'hallucinogen.jpg');
INSERT INTO images (id, image_url) values (166 ,'infectedmushroom.jpg');
INSERT INTO images (id, image_url) values (167 ,'junoreactor.jpg');
INSERT INTO images (id, image_url) values (168 ,'koxbox.jpg');
INSERT INTO images (id, image_url) values (169 ,'shpongle.jpg');
INSERT INTO images (id, image_url) values (170 ,'skazi.jpg');
INSERT INTO images (id, image_url) values (171 ,'talamasca.jpg');
INSERT INTO images (id, image_url) values (172,'50cent.jpg');
INSERT INTO images (id, image_url) values (173 ,'cardib.jpg');
INSERT INTO images (id, image_url) values (174 ,'cypresshill.jpg');
INSERT INTO images (id, image_url) values (175 ,'eminem.jpg');
INSERT INTO images (id, image_url) values (176 ,'forminor.jpg');
INSERT INTO images (id, image_url) values (177 ,'kanyewest.jpg');
INSERT INTO images (id, image_url) values (178 ,'ludacris.jpg');
INSERT INTO images (id, image_url) values (179 ,'tupakshakur.jpg');
INSERT INTO images (id, image_url) values (180 ,'wizhalifa.jpg');
INSERT INTO images (id, image_url) values (181 ,'xzibit.jpg');
INSERT INTO images (id, image_url) values (182 ,'aliciakeys.jpg');
INSERT INTO images (id, image_url) values (183 ,'blackeyedpeas.jpg');
INSERT INTO images (id, image_url) values (184 ,'ciara.jpg');
INSERT INTO images (id, image_url) values (185 ,'craigdavid.jpg');
INSERT INTO images (id, image_url) values (186 ,'fergie.jpg');
INSERT INTO images (id, image_url) values (187 ,'janellemonae.jpg');
INSERT INTO images (id, image_url) values (188 ,'justintimberlake.jpg');
INSERT INTO images (id, image_url) values (189 ,'leonalewis.jpg');
INSERT INTO images (id, image_url) values (190 ,'rihanna.jpg');
INSERT INTO images (id, image_url) values (191 ,'theweeknd.jpg');
INSERT INTO images (id, image_url) values (192 ,'aerosmith.jpg');
INSERT INTO images (id, image_url) values (193 ,'animals.jpg');
INSERT INTO images (id, image_url) values (194 ,'bonjovi.jpg');
INSERT INTO images (id, image_url) values (195 ,'eltonjohn.jpg');
INSERT INTO images (id, image_url) values (196 ,'gunsandroses.jpg');
INSERT INTO images (id, image_url) values (197 ,'ledzeppelin.jpg');
INSERT INTO images (id, image_url) values (198 ,'nirvana.jpg');
INSERT INTO images (id, image_url) values (199 ,'queen.jpg');
INSERT INTO images (id, image_url) values (200 ,'u2.jpg');
INSERT INTO images (id, image_url) values (201 ,'zztop.jpg');
INSERT INTO images (id, image_url) values (202 ,'adambeyer.jpg');
INSERT INTO images (id, image_url) values (203 ,'bobbywomack.jpg');
INSERT INTO images (id, image_url) values (204 ,'johnlegend.jpg');
INSERT INTO images (id, image_url) values (205 ,'laurynhill.jpg');
INSERT INTO images (id, image_url) values (206 ,'otisredding.jpg');
INSERT INTO images (id, image_url) values (207 ,'raycharles.jpg');
INSERT INTO images (id, image_url) values (208 ,'robertaflack.jpg');
INSERT INTO images (id, image_url) values (209 ,'samcooke.jpg');
INSERT INTO images (id, image_url) values (210 ,'thespinners.jpg');
INSERT INTO images (id, image_url) values (211 ,'victorruiz.jpg');
INSERT INTO images (id, image_url) values (212 ,'chrisliebling.jpg');
INSERT INTO images (id, image_url) values (213 ,'guiboratto.jpg');
INSERT INTO images (id, image_url) values (214 ,'jeffmills.jpg');
INSERT INTO images (id, image_url) values (215 ,'kink.jpg');
INSERT INTO images (id, image_url) values (216 ,'lenfaki.jpg');
INSERT INTO images (id, image_url) values (217 ,'moby.png');
INSERT INTO images (id, image_url) values (218 ,'prodigy.jpg');
INSERT INTO images (id, image_url) values (219 ,'radioslave.jpg');
INSERT INTO images (id, image_url) values (220 ,'umek.jpg');
INSERT INTO images (id, image_url) values (221 ,'underworld.jpg');
INSERT INTO images (id, image_url) values (222 ,'aboveandbeyond.jpg');
INSERT INTO images (id, image_url) values (223 ,'alanmorris.jpg');
INSERT INTO images (id, image_url) values (224 ,'arminvanbuuren.jpg');
INSERT INTO images (id, image_url) values (225 ,'dashberlin.jpg');
INSERT INTO images (id, image_url) values (226 ,'ferrycorsten.jpg');
INSERT INTO images (id, image_url) values (227 ,'giuseppeottaviani.jpg');
INSERT INTO images (id, image_url) values (228 ,'ilyasoloviev.jpg');
INSERT INTO images (id, image_url) values (229 ,'markuschulz.jpg');
INSERT INTO images (id, image_url) values (230 ,'sunlounger.png');
INSERT INTO images (id, image_url) values (231 ,'tiesto.jpeg');

