INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id, player_queue_id) VALUES (1, '30 seconds to Mars', true, 'Los-Angeles', 22,1,1);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id,cart_id,player_queue_id) VALUES (2, 'Linkin Park', true, 'Los-Angeles', 23,2,2);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id, player_queue_id) VALUES (3, 'Muse', true, 'London', 24,3,3);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (4, 'My chemical romance', true, 'New York', 25,4,4);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (5, 'Oasis', true, 'Los-Angeles', 26,5,5);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id ) VALUES (6, 'Red Hot Chili Peppers', true, 'Texas', 27,6,6);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (7, 'The Cranberries', true, 'Dublin', 28,7,7);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (8, 'The Cure', true, 'London', 29,8,8);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (9, 'The Smashing Pumpkins', true, 'Los-Angeles', 30,9,9);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (10,'Three Days Grace', true, 'New-York',31,10,10);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (11,'B.B. King', false, 'Chicago',32,11,11);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (12,'Eric Clapton', false, 'London',33,12,12);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (13,'Freddie King', false, 'New-York',34,13,13);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (14,'Janis Joplin', false, 'Los-Angeles',35,14,14);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (15,'Jimi Hendrix', false, 'London',36,15,15);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (16,'Joe Bonamassa', false, 'New-York',37,16,16);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (17,'Leonard Cohen', false, 'Montreal',38,17,17);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (18,'Muddy Waters', false, 'Westmont',39,18,18);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (19,'Ray Charles', false, 'New-York',40,19,19);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (20,'Tom Waits', false, 'Los-Angeles',41,20,20);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (21,'Apex', false, 'New-York',42,21,21);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (22,'Bes', false,'Saint-Petersburg',43,22,22);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (23,'Black Sun Empire', false, 'New-York',44,23,23);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (24,'High Contrast', false, 'New-York',45,24,24);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (25,'Logistics', false, 'New-York',46,25,25);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (26,'Noisia', false, 'New-York',47,26,26);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (27,'Pendulum', false, 'New-York',48,27,27);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (28,'Receptor', false, 'Moscow',49,28,28);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (29,'Teebee', false, 'New-York',50,29,29);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (30,'The Panacea', false, 'New-York',51,30,30);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (31,'Afrojack', false, 'New-York',52,31,31);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (32,'Chuckie', false, 'New-York',53,32,32);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (33,'Dada Life', false, 'New-York',54,33,33);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (34,'Dead Mau5', false, 'New-York',55,34,34);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (35,'Heiko and Maiko', false, 'New-York',56,35,35);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (36,'Klaas', false, 'New-York',57,36,36);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (37,'Sebastian Ingrosso', false, 'New-York',58,37,37);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (38,'Sebastian Leger', false, 'New-York',59,38,38);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (39,'Tocadisco', false, 'New-York',60,39,39);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (40,'Wolfgang Gartner', false, 'New-York',61,40,40);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (41,'Bob Dylan', false, 'New-York',62,41,41);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (42,'Bruce Springsteen', false, 'New-York',63,42,42);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (43,'Cat Stevens', false, 'New-York',64,43,43);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (44,'Elliot Smith', false, 'New-York',65,44,44);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (45,'Fleet Foxes', false, 'New-York',66,45,45);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (46,'Iron and Wine', false, 'New-York',67,46,46);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (47,'Johnny Cash', false, 'New-York',68,47,47);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (48,'Joni Mitchell', false, 'New-York',69,48,48);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (49,'Neil Young', false, 'New-York',70,49,49);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (50,'Nick Drake', false, 'New-York',71,50,50);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id, player_queue_id) VALUES (51,'Al Green', false, 'New-York',72,51,51);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (52,'Curtis Mayfield', false, 'New-York',73,52,52);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (53,'Funkadelic', false, 'New-York',74,53,53);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (54,'George Duke', false, 'New-York',75,54,54);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (55,'James Brown', false, 'New-York',76,55,55);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (56,'Jamiroquai', false, 'New-York',77,56,56);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (57,'Lenny Kravitz', false, 'New-York',78,57,57);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (58,'Marvin Gaye', false, 'New-York',79,58,58);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id)VALUES (59,'Prince', false, 'New-York',80,59,59);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (60,'Stevie Wonder', false, 'New-York',81,60,60);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (61,'Akon', false, 'New-York',82,61,61);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id)VALUES (62,'Beastie Boyz', false, 'New-York',83,62,62);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (63,'Flying Lotus', false, 'New-York',84,63,63);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (64,'Jay-Z', false, 'New-York',85,64,64);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (65,'Lil Wayne', false, 'New-York',86,65,65);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (66,'Lupe Fiasco', false, 'New-York',87,66,66);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (67,'Missy Elliot', false, 'New-York',88,67,67);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (68,'Snoop Dogg', false, 'New-York',89,68,68);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id)VALUES (69,'Timbaland', false, 'New-York',90,69,69);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id)VALUES (70,'Wu Tang Clan', false, 'New-York',91,70,70);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (71,'Alex Gaudino', false, 'New-York',92,71,71);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (72,'Avicii', false, 'New-York',93,72,72);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (73,'Benny Benassi', false, 'New-York',94,73,73);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (74,'Chemical Brothers', false, 'New-York',95,74,74);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (75,'Daft Punk', false, 'New-York',96,75,75);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (76,'Davig Guetta', false, 'New-York',97,76,76);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (77,'Faithless', false, 'New-York',98,77,77);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (78,'Fedde Le Grand', false, 'New-York',99,78,78);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (79,'Kaskade', false, 'New-York',100,79,79);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (80,'Swedish House Mafia', false, 'New-York',101,80,80);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id)VALUES (81,'Arctic Monkeys', false, 'New-York',102,81,81);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (82,'Coldplay', false, 'New-York',103,82,82);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (83,'Franz Ferdinand', false, 'New-York',104,83,83);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (84,'Hozier', false, 'New-York',105,84,84);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (85,'Kasabian', false, 'New-York',106,85,85);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (86,'Morrissey', false, 'New-York',107,86,86);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (87,'Placebo', false, 'New-York',108,87,87);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (88,'Radiohead', false, 'New-York',109,88,88);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (89,'The Smiths', false, 'New-York',110,89,89);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (90,'The XX', false, 'New-York',111,90,90);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (91,'Cabaret Voltaire', false, 'New-York',112,91,91);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (92,'Combichrist', false, 'New-York',113,92,92);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (93,'KMFDM', false, 'New-York',114,93,93);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (94,'Laibach', false, 'New-York',115,94,94);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (95,'Marilyn Manson', false, 'New-York',116,95,95);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (96,'Nachtmahr', false, 'New-York',117,96,96);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (97,'Rammstein', false, 'New-York',118,97,97);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (98,'Rob Zombie', false, 'New-York',119,98,98);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (99,'Skinny Puppy', false, 'New-York',120,99,99);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (100,'Suicide Commando', false, 'New-York',121,100,100);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (101,'Amy Winehouse', false, 'New-York',122,101,101);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (102,'Aretha Franklin', false, 'New-York',123,102,102);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (103,'Benny Goodman', false, 'New-York',124,103,103);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (104,'Billie Holiday', false, 'New-York',125,104,104);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (105,'Duke Ellington', false, 'New-York',126,105,105);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (106,'Ella Fitzerald', false, 'New-York',127,106,106);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (107,'Frank Sinatra', false, 'New-York',128,107,107);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (108,'Louis Armstrong', false, 'New-York',129,108,108);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (109,'Nina Simone', false, 'New-York',130,109,109);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (110,'Zaz', false, 'New-York',131,110,110);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (111,'AC DC', false, 'New-York',132,111,111);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (112,'Apocalyptica', false, 'New-York',133,112,112);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (113,'Godsmack', false, 'New-York',134,113,113);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (114,'Iron Maiden', false, 'New-York',135,114,114);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (115,'Korn', false, 'New-York',136,115,115);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (116,'Metallica', false, 'New-York',137,116,116);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (117,'Nightwish', false, 'New-York',138,117,117);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (118,'Slayer', false, 'New-York',139,118,118);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (119,'Slipknot', false, 'New-York',140,119,119);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (120,'System of a down', false, 'New-York',141,120,120);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (121,'Delerium', false, 'New-York',142,121,121);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (122,'Enigma', false, 'New-York',143,122,122);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (123,'Enya', false, 'New-York',144,123,123);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (124,'Gregorian', false, 'New-York',145,124,124);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (125,'Jean Michel Jarre', false, 'New-York',146,125,125);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (126,'Mike Oldfield', false, 'New-York',147,126,126);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (127,'Secret Garden', false, 'New-York',148,127,127);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (128,'Vangelis', false, 'Athens',149,128,128);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (129,'Yanni', false, 'Athens',150,129,129);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (130,'Yiruma', false, 'New-York',151,130,130);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (131,'Adam Walker', false, 'New-York',152,131,131);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (132,'Adele', false, 'New-York',153,132,132);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (133,'Britney Spears', false, 'New-York',154,133,133);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (134,'Bruno Mars', false, 'New-York',155,134,134);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (135,'Ed Sheeran', false, 'New-York',156,135,135);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (136,'Imagine Dragons', false, 'New-York',157,136,136);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (137,'Katy Perry', false, 'New-York',158,137,137);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (138,'Lady Gaga', false, 'New-York',159,138,138);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (139,'Maroon5', false, 'New-York',160,139,139);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (140,'Shakira', false, 'New-York',161,140,140);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (141,'Astral Projection', false, 'New-York',162,141,141);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (142,'Astrix', false, 'New-York',163,142,142);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (143,'GMS', false, 'New-York',164,143,143);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (144,'Hallucinogen', false, 'New-York',165,144,144);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (145,'Infected Mushroom', false, 'New-York',166,145,145);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (146,'Juno Reactor', false, 'New-York',167,146,146);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (147,'Koxbox', false, 'New-York',168,147,147);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id)VALUES (148,'Shpongle', false, 'New-York',169,148,148);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (149,'Skazi', false, 'New-York',170,149,149);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (150,'Talamasca', false, 'New-York',171,150,150);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (151,'50 cent', false, 'New-York',172,151,151);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (152,'Cardi B', false, 'New-York',173,152,152);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (153,'Cypress Hill', false, 'New-York',174,153,153);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (154,'Eminem', false, 'New-York',175,154,154);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (155,'Fort Minor', false, 'New-York',176,155,155);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (156,'Kanye West', false, 'New-York',177,156,156);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (157,'Ludacris', false, 'New-York',178,157,157);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (158,'2pak', false, 'New-York',179,158,158);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (159,'Wiz Khalifa', false, 'New-York',180,159,159);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (160,'Xzibit', false, 'New-York',181,160,160);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (161,'Alicia Keys', false, 'New-York',182,161,161);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (162,'Black Eyed Peas', false, 'New-York',183,162,162);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (163,'Ciara', false, 'New-York',184,163,163);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (164,'Craig David', false, 'New-York',185,164,164);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (165,'Fergie', false, 'New-York',186,165,165);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (166,'Janelle Monae', false, 'New-York',187,166,166);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (167,'Justin Timberlake', false, 'New-York',188,167,167);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (168,'Leona Lewis', false, 'New-York',189,168,168);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (169,'Rihanna', false, 'New-York',190,169,169);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (170,'The Weeknd', false, 'New-York',191,170,170);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (171,'Aerosmith', false, 'New-York',192,171,171);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (172,'The Animals', false, 'New-York',193,172,172);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id)VALUES (173,'Bon Jovi', false, 'New-York',194,173,173);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (174,'Elton John', false, 'New-York',195,174,174);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (175,'Guns and Roses', false, 'New-York',196,175,175);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (176,'Led Zeppelin', false, 'New-York',197,176,176);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (177,'Nirvana', false, 'New-York',198,177,177);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (178,'Queen', false, 'New-York',199,178,178);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (179,'U2', false, 'New-York',200,179,179);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (180,'ZZ Top', false, 'New-York',201,180,180);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (181,'Adam Beyer', false, 'New-York',202,181,181);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (182,'Bobby Womack', false, 'New-York',203,182,182);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (183,'John Legend', false, 'New-York',204,183,183);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (184, 'Lauryn Hill', false, 'New-York',205,184,184);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (185,'Otis Redding', false, 'New-York',206,185,185);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (186,'Ray Charles', false, 'New-York',207,186,186);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (187,'Roberta Flack', false, 'New-York',208,187,197);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (188,'Sam Cooke', false, 'New-York',209,188,188);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (189,'The Spinners', false, 'New-York',210,189,189);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (190,'Victor Ruiz', false, 'New-York',211,190,190);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (191,'Chris Liebling', false, 'New-York',212,191,191);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (192,'Gui Boratto', false, 'New-York',213,192,192);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (193,'Jeff Mills', false, 'New-York',214,193,193);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (194,'Kink', false, 'New-York',215,194,194);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (195,'Len Faki', false, 'New-York',216,195,195);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (196,'Moby', false, 'New-York',217,196,196);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (197,'Prodigy', false, 'New-York',218,197,197);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (198,'Radioslave', false, 'New-York',219,198,198);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (199,'Umek', false, 'New-York',220,199,199);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (200,'Underworld', false, 'New-York',221,200,200);

INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (201,'Above and Beyond', false, 'New-York',222,201,201);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (202,'Alan Morris', false, 'New-York',223,202,202);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (203,'Armin Van Buuren', false, 'New-York',224,203,203);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (204,'Dash Berlin', false, 'New-York',225,204,204);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (205,'Ferry Corsten', false, 'New-York',226,205,205);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (206,'Giuseppe Ottaviani', false, 'New-York',227,206,206);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (207,'Ilya Soloviev', false, 'New-York',228,207,207);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (208,'Markus Schulz', false, 'New-York',229,208,208);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES (209,'Sunlounger', false, 'New-York',230,209,209);
INSERT INTO site_visitors (id, login,  is_featured, location, picture_id, cart_id,player_queue_id) VALUES  (210,'Tiesto', false, 'New-York',231,210,210);
INSERT INTO site_visitors (dtype, id, login, password, cart_id, player_queue_id) VALUES ('Admin', 211, 'admin', '$2y$12$AhlUkEkij2ioKPIdSRFVW.KjM9.Ge3u/tVQ/o4RycDdxFijQbJNye',211,211 );

